# joint_limits.yaml allows the dynamics properties specified in the URDF to
# be overwritten or augmented as needed.
#
# Specific joint properties can be changed with the keys
# [max_position, min_position, max_velocity, max_acceleration]
#
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    max_position: 3.1415
    min_position: -3.1415
    has_velocity_limits: true
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 0.25
  joint_2:
    has_velocity_limits: true
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 0.25
  joint_3:
    has_velocity_limits: true
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 0.25
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 0.25
  joint_5:
    has_velocity_limits: false
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 0.25
  joint_6:
    has_velocity_limits: false
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 0.25
