gazebo: false # Whether the robot is started in simulation environment
collision_check: false # Check collisions?
command_in_topic:  jog_arm_server/frame_delta_jog_cmds_spacemouse
joint_command_in_topic: jog_arm_server/joint_delta_jog_cmds_spacemouse
command_frame:  borunte_stand_link  # TF frame that incoming cmds are given in
incoming_command_timeout:  0.5  # Stop jogging if X seconds elapse without a new cmd
joint_topic:  joint_states
move_group_name:  manipulator  # Often 'manipulator' or 'arm'
singularity_threshold:  5.5  # Slow down when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 20 # Stop when the condition number hits this
command_out_topic: position_trajectory_controller/command
planning_frame:  borunte_stand_link  # The MoveIt! planning frame. Often 'base_link'
low_pass_filter_coeff:  2.  # Larger c --> trust the filtered data more, trust the measurements less.
publish_period:  0.01  # 1/Nominal publish rate [seconds]
publish_delay: 0.005  # delay between calculation and execution start of command
scale:
  linear:  0.002  # Max linear velocity. Meters per publish_period. Units is [m/s]
  rotational:  0.004  # Max angular velocity. Rads per publish_period. Units is [rad/s]
  joint: 0.01  # Max joint angular/linear velocity. Rads or Meters per publish period. Units is [rad/s] or [m/s].
# Publish boolean warnings to this topic
warning_topic:  jog_arm_server/warning
joint_limit_margin: -0.01 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.
